apiVersion: v2
name: onecx-theme-bff
version: 0.0.0
appVersion: 0.0.0
description: Onecx theme management bff
keywords:
  - iam
  - parameters
sources:
  - https://github.com/onecx/onecx-theme-bff
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: ^0
    repository: oci://ghcr.io/onecx/charts